baseURL = "https://dc-presentations.netlify.com"
languageCode = "en-us"
title = "Learning material from Josh Medeski"
disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"

[author]
name = "Josh Medeski"

# uncomment for browsing at file:///
relativeURLs = true
uglyURLs = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true
custom_theme = "digitalcrafts.scss"
custom_theme_compile = true

[params.logo]
src = "/digitalcrafts-logo.png"
alt = "DigitalCrafts Logo"

[params.reveal_hugo.custom_theme_options]
targetPath = "css/digitalcrafts.css"
enableSourceMap = true